### ISSUE TITLE
[Feature] Embedings read 

### ISSUE THREAD

**Issue by Rogal80** [poipoi300/auto-sd-krita-ext-xl#6]
**Is your feature request related to a problem? Please describe.**
HI, is there any chance that embedings will work in krita ? Right now, when I check in the image browser, there are no embeddings in the description. It's just text in the prompt.

**Comment by poipoi300** [comment]
I don't understand what you mean. Embeddings like textual inversion? Or like the metadata about prompts + settings? Both of these are saved in the PNG's as normal. Just the final image that doesn't get them.
![msedge_RIM4JbKmHU](https://github.com/poipoi300/auto-sd-krita-ext-xl/assets/80789459/143f3478-8e0a-4ce0-8901-be0130feabb7)

**Comment by Rogal80** [comment]
Yes, the textual inversion is correct. So, it's just missing metadata? And is TI working?

**Comment by poipoi300** [comment]
Yes textual inversion is working. Metadata for the final image is not planned because it doesn't make much sense to me. To really have something representative of how the image was made, it would need to be complex to the point that just showing the krita layers would be better. Or a timelapse of making the image. Or the .kra file itself.
